#ifndef _IOT_PLATFORM_SENSOR_H_
#define _IOT_PLATFORM_SENSOR_H_

#define SENSOR_ID 8
#define SENSOR_NAME "[SENSOR:USERNAME]"
#define SENSOR_PASSWORD "[SENSOR:PASSWORD]"

#define SENSOR_HUMEDAD_HUMEDAD_SALON "SENSOR_HUMEDAD_HUMEDAD_SALON_CONFIGURATION_ID"
#define SENSOR_PRESION_PRESION_SALON "SENSOR_PRESION_PRESION_SALON_CONFIGURATION_ID"
#define SENSOR_TEMPERATURA_TEMPERATURA_SALON "SENSOR_TEMPERATURA_TEMPERATURA_SALON_CONFIGURATION_ID"
#endif