#ifndef _IOT_PLATFORM_SENSOR_H_
#define _IOT_PLATFORM_SENSOR_H_

#define SENSOR_ID 1
#define SENSOR_NAME "bme280"
#define SENSOR_PASSWORD "123456789"

#define SENSOR_HUMEDAD_HUMEDAD_HABITACION "6"
#define SENSOR_PRESION_PRESION_HABITACION "5"
#define SENSOR_TEMPERATURA_TEMPERATURA_HABITACION "4"
#endif